### ISSUE TITLE
非实验室内网，远程访问服务器方法

### ISSUE THREAD

**Issue by stonycat** [ISCAS007/PaperReading#9]
# SSH 指定密钥，连接远程服务器。
——————————————————————————————
## 原理
很简单，使用ssh-keygen 在主机A上生成公钥和密钥，将生成的公钥拷贝到远程机器主机B上后,就可以使用ssh命令无需密码登录到另外一台机器主机B上。
## 步骤
1. 生成公钥和私钥文件id_rsa和id_rsa.pub 
`ssh-keygen -t rsa` 

2. ssh-cop-id命令会将指定的公钥文件复制到远程计算机
`ssh-copy-id -i ~/.ssh/id_rsa.pub '-p 2222 root@10.0.0.39`

3. 然后ssh登陆主机B验证是否需要密码
 `ssh root@10.0.0.39`

**Comment by yzbx** [comment]
... 非实验室内网，应该会报警说ip 10.0.0.39找不到。

**Comment by yzbx** [comment]
@stonycat 在实验室无法尝试,(在实验室用路由器,实际也属于实验室内网,在宿舍应该就访问不到了)
用路由器的话,直接连也没问题,只是要输密码.

**Comment by yzbx** [comment]
# IPV6 访问实验室服务器
按照zzm的实践，可以用IPV6远程访问实验室服务器
